const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.Compare
	];
};
self.C3_JsPropNameTable = [
	{Text: 0},
	{Text2: 0},
	{UM: 0},
	{UM1: 0},
	{DOIS: 0},
	{DOIS2: 0},
	{Text3: 0},
	{CLIENTE: 0},
	{CLIENTE2: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{recebi: 0},
	{Text7: 0},
	{troco: 0},
	{Sprite: 0},
	{Text8: 0},
	{Text9: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text10: 0},
	{Text11: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Text12: 0},
	{Text13: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Text14: 0},
	{Text15: 0},
	{Text16: 0},
	{Text17: 0},
	{Sprite9: 0},
	{Text18: 0},
	{Button: 0},
	{Button2: 0},
	{Button3: 0},
	{Touch: 0},
	{Browser: 0},
	{AL: 0},
	{AL1: 0},
	{AU: 0},
	{AU1: 0},
	{Text19: 0},
	{Text20: 0},
	{Sprite10: 0},
	{quantidade: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	UM: class extends self.ITextInputInstance {},
	UM1: class extends self.ITextInputInstance {},
	DOIS: class extends self.ITextInputInstance {},
	DOIS2: class extends self.ITextInputInstance {},
	Text3: class extends self.ITextInstance {},
	CLIENTE: class extends self.ITextInputInstance {},
	CLIENTE2: class extends self.ITextInputInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	recebi: class extends self.ITextInputInstance {},
	Text7: class extends self.ITextInstance {},
	troco: class extends self.ITextInputInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text14: class extends self.ITextInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	Text17: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Text18: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AL: class extends self.ITextInputInstance {},
	AL1: class extends self.ITextInputInstance {},
	AU: class extends self.ITextInputInstance {},
	AU1: class extends self.ITextInputInstance {},
	Text19: class extends self.ITextInstance {},
	Text20: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}